Ad Hoc Charge & (Category) api docs
tutorcruncher/tc-api-docs pull request #61
Opened 2021-12-10 15:48 UTC by HenryTraill

2021-12-17 10:33 UTC, alextford11 requested changes

2021-12-17 10:33 UTC, alextford11 commented on pages/adhoccharges/ad-hoc-charge-object.json
> +    "name": "Registration fee"
Try to use example as much as possible please, strings and integers are easy to do, FK i don't care

2021-12-17 10:33 UTC, alextford11 commented on pages/adhoccharges/adhoccharges.yml
> +
remove extra line

2021-12-17 10:33 UTC, alextford11 commented on pages/adhoccharges/create-an-ad-hoc-charge.json
> +    "name": "Registration fee"
more examples plz

2021-12-17 10:33 UTC, alextford11 commented on pages/adhoccharges/create-an-ad-hoc-charge.json
> +    "name": "Registration fee"
just use the same all over and copy and paste it in

2021-12-17 10:33 UTC, alextford11 commented on pages/adhoccharges/create-an-ad-hoc-charge.md
> +`charge_client` and `client` or `pay_contractor` and `contractor`.
description?

2021-12-17 10:33 UTC, alextford11 commented on pages/adhoccharges/create-an-ad-hoc-charge.py
> +    'date_occurred': datetime.datetime(2021, 1, 1),
description?

2021-12-17 10:33 UTC, alextford11 commented on pages/adhoccharges/get-an-ad-hoc-charge.json
> +  "category": {
!

2021-12-17 10:33 UTC, alextford11 commented on pages/adhoccharges/update-an-ad-hoc-charge.json
> +  "category": {
!

2021-12-17 10:33 UTC, alextford11 commented on pages/adhoccharges/update-an-ad-hoc-charge.md
> +Updating an Ad Hoc Charge can be completed by simply supplying the `date_occurred`, `category`, any fields to
description?

2021-12-17 10:33 UTC, alextford11 commented on pages/adhoccharges/update-an-ad-hoc-charge.py
> +    'service': 26,
description?

2021-12-17 10:33 UTC, alextford11 commented on pages/ahc-categories/ad-hoc-charge-category-object.json
> +}
new line

2021-12-17 10:33 UTC, alextford11 commented on pages/ahc-categories/ad-hoc-charge-category-object.json
> +{
!

2021-12-17 10:33 UTC, alextford11 commented on pages/ahc-categories/ad-hoc-charge-category-object.md
> +Returns the details of an existing ah hoc charge category. You only need to specify the unique
```suggestion
Returns the details of an existing Ad Hoc Charge Category. You only need to specify the unique
```

2021-12-17 10:33 UTC, alextford11 commented on pages/ahc-categories/ad-hoc-charge-category-object.md
> +`id` of the ad hoc charge category to get the correct details.
```suggestion
`id` of the Ad Hoc Charge Category to get the correct details.
```

2021-12-17 10:33 UTC, alextford11 commented on pages/ahc-categories/list-all-ad-hoc-charge-categories.json
> +    {
!

2021-12-17 10:33 UTC, alextford11 commented on pages/ahc-categories/list-all-ad-hoc-charge-categories.md
> +Returns a list of your ad hoc charge categories. The ad hoc charge categories are sorted by `id`, with
```suggestion
Returns a list of your Ad Hoc Charge Categories. The Ad Hoc Charge Categories are sorted by `id`, with 
```

2021-12-17 10:33 UTC, alextford11 commented on pages/ahc-categories/list-all-ad-hoc-charge-categories.md
> +the largest id first.
is it?

2021-12-17 11:57 UTC, HenryTraill commented on pages/ahc-categories/list-all-ad-hoc-charge-categories.md
> +the largest id first.
no

2021-12-21 17:09 UTC, alextford11 requested changes

2021-12-21 17:09 UTC, alextford11 commented on pages/ahc-categories/ad-hoc-charge-category-object.md
> +`id` of the Ah Hoc Charge Category to get the correct details.
!

2021-12-21 17:09 UTC, alextford11 commented on pages/adhoccharges/delete-an-ad-hoc-charge.json
> +  "message": "Successfully deleted Ad Hoc Charge 37: 37: Registration fee"
2 `37:`?

2022-01-04 10:09 UTC, merged